### ISSUE TITLE
Extension unmutes twitch when ad plays while already muted.

### ISSUE THREAD

**Issue by LogicEngineer** [dinotrooper/twitch_ad_muter#1]
Firefox 122.0 (64-bit)
Extension Version: 1.4

The sequence of what happened:
Watching Twitch stream.
Manually muted Twitch stream. 
Switched to another tab while stream was muted. 
Forget about muted stream. 
Jump scared when forgotten stream suddenly unmutes as ad starts playing. 

I have done no additional testing on this issue and have only used this extension for a few hours. 
Is it possible to check the muted status before toggling the mute button? Is the extension already supposed to do this?

Great extension though!

**Comment by dinotrooper** [comment]
> Is it possible to check the muted status before toggling the mute button? Is the extension already supposed to do this?

I didn't consider this scenario. Sorry for the jump scare! Haha. I have an idea in mind. I will try to have something in a few days.

**Comment by dinotrooper** [comment]
This issue should be fixed. @LogicEngineer can you double check it for me?

**Comment by LogicEngineer** [comment]
Looks like that fixed it! Awesome!

Joe P.
